begin;

create temp table fisheries_lr_staging (
    nhs            varchar(10),
    lr_fishfarming  boolean,
    lr_goatrearing  boolean
);

insert into fisheries_lr_staging values
  ('NHS001', true,  false),
  ('NHS002', false, true),
  ('NHS003', false, true),
  ('NHS004', false, true),
  ('NHS005', false, true),
  ('NHS006', true,  false),
  ('NHS007', false, true),
  ('NHS008', false, true),
  ('NHS009', true,  false),
  ('NHS010', true,  false),
  ('NHS011', false, true),
  ('NHS012', false, true),
  ('NHS013', true,  false),
  ('NHS014', false, true),
  ('NHS015', false, true),
  ('NHS016', false, true),
  ('NHS017', false, true),
  ('NHS018', false, true),
  ('NHS019', false, true),
  ('NHS021', false, true),
  ('NHS022', false, true),
  ('NHS023', false, true),
  ('NHS024', true,  false),
  ('NHS025', false, true),
  ('NHS026', true,  false),
  ('NHS027', true,  false),
  ('NHS028', false, true),
  ('NHS029', false, true),
  ('NHS030', false, true),
  ('NHS031', false, true),
  ('NHS032', true,  false),
  ('NHS033', true,  false),
  ('NHS034', false, true),
  ('NHS035', false, true),
  ('NHS036', false, true),
  ('NHS038', false, true),
  ('NHS039', false, true),
  ('NHS040', false, true),
  ('NHS041', false, true),
  ('NHS042', false, true),
  ('NHS043', false, true),
  ('NHS044', false, true),
  ('NHS045', false, true),
  ('NHS046', false, true),
  ('NHS047', false, true),
  ('NHS048', false, true),
  ('NHS050', false, true),
  ('NHS051', false, true),
  ('NHS052', false, true),
  ('NHS053', false, true),
  ('NHS054', false, true),
  ('NHS055', false, true),
  ('NHS056', true,  false),
  ('NHS057', false, true),
  ('NHS058', false, true),
  ('NHS059', false, true),
  ('NHS060', false, true),
  ('NHS061', false, true),
  ('NHS062', false, true),
  ('NHS063', false, true),
  ('NHS064', false, true),
  ('NHS066', false, true),
  ('NHS067', false, true),
  ('NHS068', false, true),
  ('NHS069', false, true),
  ('NHS070', false, true),
  ('NHS071', true,  false),
  ('NHS072', false, true),
  ('NHS073', false, true),
  ('NHS074', false, true),
  ('NHS075', true,  false),
  ('NHS076', false, true),
  ('NHS077', false, true),
  ('NHS078', true,  false),
  ('NHS079', false, true),
  ('NHS080', false, true),
  ('NHS081', true,  false),
  ('NHS082', false, true),
  ('NHS083', false, true),
  ('NHS084', false, true),
  ('NHS086', false, true),
  ('NHS087', false, true),
  ('NHS088', false, true),
  ('NHS089', false, true),
  ('NHS091', false, true),
  ('NHS092', false, true),
  ('NHS093', true,  false),
  ('NHS094', true,  false),
  ('NHS096', false, true),
  ('NHS097', false, true),
  ('NHS098', false, true),
  ('NHS099', false, true),
  ('NHS100', false, true),
  ('NHS101', false, true),
  ('NHS102', false, true),
  ('NHS103', false, true),
  ('NHS104', false, true),
  ('NHS105', false, true),
  ('NHS106', false, true),
  ('NHS107', false, true),
  ('NHS108', false, true),
  ('NHS109', false, true),
  ('NHS110', false, true),
  ('NHS112', true,  false),
  ('NHS113', false, true),
  ('NHS114', false, true),
  ('NHS116', false, true),
  ('NHS117', false, true),
  ('NHS118', true,  false),
  ('NHS119', true,  false),
  ('NHS120', false, true),
  ('NHS121', true,  false),
  ('NHS122', false, true),
  ('NHS123', false, true),
  ('NHS124', true,  false),
  ('NHS125', false, true),
  ('NHS126', false, true),
  ('NHS127', false, true),
  ('NHS128', false, true),
  ('NHS129', false, true),
  ('NHS130', false, true),
  ('NHS132', false, true),
  ('NHS132', false, true),
  ('NHS133', true,  false),
  ('NHS134', false, true),
  ('NHS135', false, true),
  ('NHS136', false, true),
  ('NHS137', false, true),
  ('NHS138', false, true),
  ('NHS140', false, true),
  ('NHS141', false, true),
  ('NHS142', false, true),
  ('NHS144', false, true),
  ('NHS145', false, true),
  ('NHS146', false, true),
  ('NHS147', false, true),
  ('NHS148', false, true),
  ('NHS149', false, true),
  ('NHS150', false, true),
  ('NHS153', false, true),
  ('NHS155', true,  false),
  ('NHS156', false, true),
  ('NHS157', true,  false),
  ('NHS160', false, true),
  ('NHS161', false, true),
  ('NHS162', false, true),
  ('NHS163', false, true),
  ('NHS164', false, true),
  ('NHS165', false, true),
  ('NHS166', false, true),
  ('NHS167', true,  false),
  ('NHS168', false, true),
  ('NHS169', false, true),
  ('NHS170', true,  false),
  ('NHS171', false, true),
  ('NHS172', false, true),
  ('NHS173', false, true),
  ('NHS174', false, true),
  ('NHS175', false, true),
  ('NHS176', false, true),
  ('NHS177', false, true),
  ('NHS178', false, true),
  ('NHS179', false, true),
  ('NHS180', false, true),
  ('NHS181', false, true),
  ('NHS182', false, true),
  ('NHS183', true,  false),
  ('NHS184', false, true),
  ('NHS185', true,  false),
  ('NHS186', true,  false),
  ('NHS187', true,  false),
  ('NHS188', false, true),
  ('NHS189', false, true),
  ('NHS190', true,  false),
  ('NHS192', false, true),
  ('NHS193', false, true),
  ('NHS194', false, true),
  ('NHS195', false, true),
  ('NHS197', false, true),
  ('NHS198', false, true),
  ('NHS200', false, true),
  ('NHS200', false, true),
  ('NHS201', true,  false),
  ('NHS202', false, true),
  ('NHS203', false, true),
  ('NHS204', false, true),
  ('NHSU100', false, true),
  ('NHSU101', false, true),
  ('NHSU103', false, true),
  ('NHSU105', false, true),
  ('NHSU106', false, true),
  ('NHSU107', false, true),
  ('NHSU108', false, true),
  ('NHSU116', false, true),
  ('NHSU117', false, true),
  ('NHSU118', false, true),
  ('NHSU121', false, true),
  ('NHSU122', false, true),
  ('NHSU128', false, true),
  ('NHSU131', false, true),
  ('NHSU132', false, true);

update public.fishers f
set
    lr_fishfarming = s.lr_fishfarming,
    lr_goatrearing = s.lr_goatrearing
from (
    select distinct on (nhs) nhs, lr_fishfarming, lr_goatrearing
    from fisheries_lr_staging
) s
where f.nhs = s.nhs;

drop table fisheries_lr_staging;

update fishers set lr_goatrearing=false where lr_fishfarming=true;
update fishers set lr_fishfarming=false where lr_goatrearing=true;

Delete from notes where note='Follow-up flag set';

commit;
